Confirm installation success and remove debug output in spigot-server script

diff --git a/files/usr/local/bin/spigot-server b/files/usr/local/bin/spigot-server
--- a/files/usr/local/bin/spigot-server
+++ b/files/usr/local/bin/spigot-server
@@ -12,13 +12,17 @@ case $1 in
         echo "Checking Spigot installation status..."
         spigot_version=$(/bin/bash /usr/local/spigot/spigot_version.sh)
 
-        echo "Spigot version: "
-        echo "$spigot_version"
-
         if [ "$spigot_version" = "NONE" ]
         then
             echo "Spigot is not installed. Installing now..."
             /bin/bash /usr/local/spigot/spigot_install.sh
+
+            # Bail if installation failed.
+            if [ "$?" -gt "0" ]
+            then
+                echo "Unable to start Spigot: Failed to run Spigot installation"
+                exit 1
+            fi
         fi
 
         echo "Starting Spigot server..."
